# Generated by Django 5.2.16 on 2026-07-09 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=255, verbose_name='dirección')),
                ('ciudad', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('residencial', 'Residencial'), ('comercial', 'Comercial')], default='residencial', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_propietario', models.CharField(max_length=200, verbose_name='nombre completo del propietario')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='costo del departamento')),
                ('numero_cuartos', models.PositiveSmallIntegerField(verbose_name='número de cuartos')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='inmuebles.edificio')),
            ],
        ),
    ]
